React.Children = {}
React.createRef = function() {}
React.Component = function() {}
React.PureComponent = function() {}
React.createContext = function() {}
React.forwardRef = function() {}
React.lazy = function() {}
React.memo = function() {}
React.useCallback = function() {}
React.useContext = function() {}
React.useEffect = function() {}
React.useImperativeHandle = function() {}
React.useDebugValue = function() {}
React.useLayoutEffect = function() {}
React.useMemo = function() {}
React.useReducer = function() {}
React.useRef = function() {}
React.useState = function() {}
React.Fragment = function() {}
React.StrictMode = function() {}
React.Suspense = function() {}
React.createElement = function() {}
React.cloneElement = function() {}
React.createFactory = function() {}
React.isValidElement = function() {}
React.version = ""
React.unstable_ConcurrentMode = function() {}
React.unstable_Profiler = function() {}
React.unstable_scheduleCallback = function() {}
React.unstable_cancelCallback = function() {}
React.unstable_now = function() {}
React.unstable_shouldYield = function() {}
React.unstable_runWithPriority = function() {}
React.unstable_getCurrentPriorityLevel = function() {}
React.unstable_ImmediatePriority = function() {}
React.unstable_UserBlockingPriority = function() {}
React.unstable_NormalPriority = function() {}
React.unstable_LowPriority = function() {}
React.unstable_IdlePriority = function() {}
React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED = {}

ReactDOM.createPortal = function() {}
ReactDOM.findDOMNode = function() {}
ReactDOM.hydrate = function() {}
ReactDOM.render = function() {}
ReactDOM.unstable_renderSubtreeIntoContainer = function() {}
ReactDOM.unmountComponentAtNode = function() {}
ReactDOM.unstable_createPortal = function() {}
ReactDOM.unstable_batchedUpdates = function() {}
ReactDOM.unstable_interactiveUpdates = function() {}
ReactDOM.flushSync = function() {}
ReactDOM.unstable_createRoot = function() {}
ReactDOM.unstable_flushControlled = function() {}
ReactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED = {}

emotion = {}
emotion.css = function() {}
