#!/usr/bin/env bash

set -e
set -o pipefail

#echo "Installing NPM deps..."
#yarn install --frozen-lockfile
#
#echo "Running Clojure tests..."
#clojure -A:test -m uix.test-runner
#
#echo "<div id=root></div><script src="out/main.js"></script>" > index.html

echo "Building ClojureScript dev tests..."
clojure -A:test -m cljs.main -c uix.test-runner

echo "Running ClojureScript dev tests..."
scripts/test.js $(pwd)

echo "Building ClojureScript prod tests..."
rm -rf out
clojure -A:test -m cljs.main -O advanced \
  -co '{:infer-externs true :closure-defines {goog.DEBUG false}}' \
  -c uix.test-runner

echo "Running ClojureScript prod tests..."
scripts/test.js $(pwd)
