#!/usr/bin/env bash

set -e
set -o pipefail

echo "Installing NPM deps..."
yarn install --frozen-lockfile

echo "Running Clojure tests..."
clojure -A:test -m uix.test-runner

echo "Building ClojureScript tests..."
clojure -A:test -m cljs.main -c uix.test-runner

echo "<div id=root></div><script src="out/main.js"></script>" > index.html

echo "Running ClojureScript tests..."
scripts/test.js $(pwd)
